#!/bin/bash
#  Copyright Matus Chochlik.
#  Distributed under the Boost Software License, Version 1.0.
#  See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#
mkdir -p "${HOME}/.config/eagine/systemd" &&\
cp -v -r \
	"$(dirname ${0})/execute" \
	"$(dirname ${0})/ssh-bridge" \
	"$(dirname ${0})/ssh-bridge-cmd/" \
	"${HOME}/.config/eagine/" &&\
mkdir -p "${HOME}/.config/systemd/user/" &&\
cp -v -r $(dirname ${0})/systemd/* "${HOME}/.config/systemd/user/" &&\
[[ -x $(which systemctl) ]] && systemctl --user daemon-reload &&\
echo "Success"
