msgbus:
  asio_local_stream: true
  router:
    address:
      - /var/run/eagine/msgbus-service.socket
    id_major: 1000
    id_count: 100
  sudoku:
    helper@debug:
      count: 4
      max_recursion: 2
    helper:
      count: 8
      max_recursion: 2

