#!/bin/sh
#  Copyright Matus Chochlik.
#  Distributed under the Boost Software License, Version 1.0.
#  See accompanying file LICENSE_1_0.txt or copy at
#  https://www.boost.org/LICENSE_1_0.txt
#
exec ${EAGINE_PREFIX}/bin/eagine-msgbus-bridge \
	--config-group service

